package life.munay.core.resusables.composables.themes

import androidx.compose.ui.graphics.Color

data class ExtendedColorScheme(
    var accent1: Color,
    var accent10: Color,
    var accent2: Color,
    var accent3: Color,
    var accent4: Color,
    var accent5: Color,
    var accent6: Color,
    var accent7: Color,
    var accent8: Color,
    var accent9: Color,
    var backgroundContent: Color,
    var backgroundScreen: Color,
    var black: Color,
    var border: Color,
    var error: Color,
    var grey100: Color,
    var grey200: Color,
    var grey300: Color,
    var grey400: Color,
    var grey500: Color,
    var grey50: Color,
    var grey600: Color,
    var grey700: Color,
    var grey800: Color,
    var grey900: Color,
    var information: Color,
    var input: Color,
    var primary: Color,
    var secondary: Color,
    var success: Color,
    var tertiary: Color,
    var textHintOrDisabled: Color,
    var textPrimary: Color,
    var textSecondary: Color,
    var warning: Color,
    var white: Color
) {
    companion object {
        fun lightDefault(): ExtendedColorScheme =
            ExtendedColorScheme(
                accent1 = AppColor.Accent1Light,
                accent10 = AppColor.Accent10Light,
                accent2 = AppColor.Accent2Light,
                accent3 = AppColor.Accent3Light,
                accent4 = AppColor.Accent4Light,
                accent5 = AppColor.Accent5Light,
                accent6 = AppColor.Accent6Light,
                accent7 = AppColor.Accent7Light,
                accent8 = AppColor.Accent8Light,
                accent9 = AppColor.Accent9Light,
                backgroundContent = AppColor.BackgroundContentLight,
                backgroundScreen = AppColor.BackgroundScreenLight,
                black = AppColor.BlackLight,
                border = AppColor.BorderLight,
                error = AppColor.ErrorLight,
                grey100 = AppColor.Grey100Light,
                grey200 = AppColor.Grey200Light,
                grey300 = AppColor.Grey300Light,
                grey400 = AppColor.Grey400Light,
                grey500 = AppColor.Grey500Light,
                grey50 = AppColor.Grey50Light,
                grey600 = AppColor.Grey600Light,
                grey700 = AppColor.Grey700Light,
                grey800 = AppColor.Grey800Light,
                grey900 = AppColor.Grey900Light,
                information = AppColor.InformationLight,
                input = AppColor.InputLight,
                primary = AppColor.PrimaryLight,
                secondary = AppColor.SecondaryLight,
                success = AppColor.SuccessLight,
                tertiary = AppColor.TertiaryLight,
                textHintOrDisabled = AppColor.TextHintOrDisabledLight,
                textPrimary = AppColor.TextPrimaryLight,
                textSecondary = AppColor.TextSecondaryLight,
                warning = AppColor.WarningLight,
                white = AppColor.WhiteLight
            )

        fun darkDefault(): ExtendedColorScheme =
            ExtendedColorScheme(
                accent1 = AppColor.Accent1Dark,
                accent10 = AppColor.Accent10Dark,
                accent2 = AppColor.Accent2Dark,
                accent3 = AppColor.Accent3Dark,
                accent4 = AppColor.Accent4Dark,
                accent5 = AppColor.Accent5Dark,
                accent6 = AppColor.Accent6Dark,
                accent7 = AppColor.Accent7Dark,
                accent8 = AppColor.Accent8Dark,
                accent9 = AppColor.Accent9Dark,
                backgroundContent = AppColor.BackgroundContentDark,
                backgroundScreen = AppColor.BackgroundScreenDark,
                black = AppColor.BlackDark,
                border = AppColor.BorderDark,
                error = AppColor.ErrorDark,
                grey100 = AppColor.Grey100Dark,
                grey200 = AppColor.Grey200Dark,
                grey300 = AppColor.Grey300Dark,
                grey400 = AppColor.Grey400Dark,
                grey500 = AppColor.Grey500Dark,
                grey50 = AppColor.Grey50Dark,
                grey600 = AppColor.Grey600Dark,
                grey700 = AppColor.Grey700Dark,
                grey800 = AppColor.Grey800Dark,
                grey900 = AppColor.Grey900Dark,
                information = AppColor.InformationDark,
                input = AppColor.InputDark,
                primary = AppColor.PrimaryDark,
                secondary = AppColor.SecondaryDark,
                success = AppColor.SuccessDark,
                tertiary = AppColor.TertiaryDark,
                textHintOrDisabled = AppColor.TextHintOrDisabledDark,
                textPrimary = AppColor.TextPrimaryDark,
                textSecondary = AppColor.TextSecondaryDark,
                warning = AppColor.WarningDark,
                white = AppColor.WhiteDark
            )
    }
}
